export const THEME_COLORS = {
  BACKGROUND_LIGHT: '#f8fafc',
  BACKGROUND_PAPER: '#ffffff',
  PRIMARY_BLUE: '#2563eb',
  PRIMARY_BLUE_HOVER: '#1e55c9',
  TEXT_PRIMARY: '#111827',
  TEXT_SECONDARY: '#6b7280',
  SIDEBAR_DARK: '#1f2937',
  SIDEBAR_TEXT_LIGHT: '#f9fafb',
  SIDEBAR_TEXT_SECONDARY: '#d1d5db',
} as const

export const DIMENSIONS = {
  SIDEBAR_WIDTH: 300,
  LOGIN_BOX_WIDTH: 320,
  DELAY_LOGIN_MS: 800,
  BORDER_RADIUS_LARGE: 15,
  BORDER_RADIUS_MEDIUM: 12,
  BORDER_RADIUS_SMALL: 2,
} as const

export const SPACING = {
  PAPER_PADDING: 3,
  SIDEBAR_PADDING: '32px 20px',
  BUTTON_PADDING: '12px 20px',
} as const